# Generated by Django 5.1.6 on 2025-02-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anel",
            name="imagem_anel",
            field=models.URLField(max_length=255),
        ),
    ]
