# Generated by Django 5.1.6 on 2025-02-13 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("anel", "0002_alter_anel_imagem_anel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="anel",
            options={"verbose_name": "Anel", "verbose_name_plural": "Aneis"},
        ),
    ]
